import fs from "node:fs/promises";
import path from "node:path";
import type { ProjectSettings } from "@/lib/db/schema";
import { assertInsideRoot } from "@/lib/security/paths";
import type { VisualSelection } from "@/lib/visual-selector/types";

export type ProjectFileChange = {
  relativePath: string;
  content: string;
  description: string;
  requiresExistingSource?: boolean;
};

export type ProjectFileSnapshot = {
  workspacePath: string;
  files: Array<{
    relativePath: string;
    content: string | null;
  }>;
};

export type GeneratedPagePlan = {
  route: string;
  componentName: string;
  affectedFiles: string[];
  changes: ProjectFileChange[];
};

export type DependencyPolicyDecision = {
  addedPackages: string[];
  requiresApproval: boolean;
  blocked: boolean;
  reason: string;
  auditCommand: string | null;
};

export type DependencyApprovalRecord = {
  projectId: string;
  packages: string[];
  approvedAt: string;
};

const SOURCE_EXTENSIONS = new Set([".ts", ".tsx", ".css", ".json", ".md", ".mjs"]);
const TRANSIENT_PATH_SEGMENTS = new Set(["node_modules", ".next", ".turbo", "dist", "out", "logs"]);

export function resolveRouteFromPrompt(prompt: string, defaultRoute = "/") {
  const explicitRoute = prompt.match(/\/(?:[a-z0-9]+(?:-[a-z0-9]+)*)(?:\/[a-z0-9]+(?:-[a-z0-9]+)*)*/i)?.[0];

  if (explicitRoute) {
    return normalizeRoute(explicitRoute);
  }

  if (/landing|home|homepage/i.test(prompt)) {
    return "/";
  }

  if (/dashboard/i.test(prompt)) {
    return "/dashboard";
  }

  return normalizeRoute(defaultRoute);
}

export function createGeneratedPagePlan(input: { route: string; title: string; brief: string }): GeneratedPagePlan {
  const route = normalizeRoute(input.route);
  const segmentPath = route === "/" ? "" : route.slice(1);
  const componentName = componentNameFromRoute(route);
  const componentFileName = kebabCase(componentName);
  const routeRoot = path.posix.join("app", segmentPath);
  const pagePath = path.posix.join(routeRoot, "page.tsx");
  const componentPath = path.posix.join(routeRoot, "components", `${componentFileName}.tsx`);

  const changes = [
    {
      relativePath: pagePath,
      description: `Create route ${route}`,
      content: `import { ${componentName} } from './components/${componentFileName}'\n\nexport default function Page() {\n  return <${componentName} />\n}\n`,
    },
    {
      relativePath: componentPath,
      description: `Create ${componentName} component`,
      content: `type ${componentName}Props = {\n  title?: string\n}\n\nexport const ${componentName} = ({ title = '${escapeSingleQuoted(input.title)}' }: ${componentName}Props) => {\n  return (\n    <main className="app-shell page-shell" data-builder-id="${kebabCase(componentName)}-page" data-builder-component="${componentName}">\n      <section className="hero-section" data-builder-id="${kebabCase(componentName)}-hero" data-builder-component="${componentName}">\n        <p>Generated by AppLoop</p>\n        <h1>{title}</h1>\n        <p>${escapeJsxText(input.brief)}</p>\n      </section>\n    </main>\n  )\n}\n`,
    },
  ];

  return {
    route,
    componentName,
    affectedFiles: changes.map((change) => change.relativePath),
    changes,
  };
}

export async function inspectProjectSourceFile(workspacePath: string, relativePath: string) {
  const filePath = resolveProjectFilePath(workspacePath, relativePath);

  return fs.readFile(filePath, "utf8");
}

export async function applyProjectFileChanges(workspacePath: string, changes: ProjectFileChange[], inspectedFiles = new Set<string>()) {
  for (const change of changes) {
    if (change.requiresExistingSource && !inspectedFiles.has(change.relativePath)) {
      throw new Error(`Source inspection is required before editing ${change.relativePath}.`);
    }
  }

  const snapshot = await createProjectFileSnapshot(workspacePath, changes.map((change) => change.relativePath));

  for (const change of changes) {
    const targetPath = resolveProjectFilePath(workspacePath, change.relativePath);

    await fs.mkdir(path.dirname(targetPath), { recursive: true });
    await fs.writeFile(targetPath, change.content, "utf8");
  }

  return {
    affectedFiles: changes.map((change) => change.relativePath),
    snapshot,
  };
}

export async function createProjectFileSnapshot(workspacePath: string, relativePaths: string[]): Promise<ProjectFileSnapshot> {
  const files = await Promise.all(
    relativePaths.map(async (relativePath) => {
      const targetPath = resolveProjectFilePath(workspacePath, relativePath);

      try {
        return { relativePath, content: await fs.readFile(targetPath, "utf8") };
      } catch (error) {
        if (isMissingPathError(error)) {
          return { relativePath, content: null };
        }

        throw error;
      }
    }),
  );

  return { workspacePath, files };
}

export async function rollbackProjectFileSnapshot(snapshot: ProjectFileSnapshot) {
  for (const file of snapshot.files) {
    const targetPath = resolveProjectFilePath(snapshot.workspacePath, file.relativePath);

    if (file.content === null) {
      await fs.rm(targetPath, { force: true });
      continue;
    }

    await fs.mkdir(path.dirname(targetPath), { recursive: true });
    await fs.writeFile(targetPath, file.content, "utf8");
  }
}

export async function locateVisualSelectionInSource(workspacePath: string, selection: VisualSelection) {
  const candidates = selection.inspectorId
    ? [`data-builder-id="${selection.inspectorId}"`]
    : [selection.preferredSelector.startsWith(".") ? selection.preferredSelector.slice(1) : selection.preferredSelector].filter((candidate): candidate is string => Boolean(candidate));
  const sourceFiles = await listProjectSourceFiles(workspacePath);
  const matches = [];

  for (const relativePath of sourceFiles) {
    const content = await inspectProjectSourceFile(workspacePath, relativePath);

    for (const candidate of candidates) {
      const index = content.indexOf(candidate);

      if (index >= 0) {
        matches.push({ relativePath, selector: candidate, index });
        break;
      }
    }
  }

  return {
    matches,
    ambiguous: matches.length > 1,
    found: matches.length > 0,
  };
}

export function evaluateDependencyPolicy(input: {
  beforePackageJson: string;
  afterPackageJson: string;
  packageInstallPolicy: ProjectSettings["packageInstallPolicy"];
}): DependencyPolicyDecision {
  const before = parsePackageDependencies(input.beforePackageJson);
  const after = parsePackageDependencies(input.afterPackageJson);
  const addedPackages = [...after].filter((packageName) => !before.has(packageName)).sort();

  if (addedPackages.length === 0) {
    return { addedPackages, requiresApproval: false, blocked: false, reason: "No package changes detected.", auditCommand: null };
  }

  const auditCommand = "npm audit --audit-level=moderate";

  if (input.packageInstallPolicy === "auto") {
    return { addedPackages, requiresApproval: false, blocked: false, reason: "Package installation is automatic for this project.", auditCommand };
  }

  if (input.packageInstallPolicy === "never") {
    return { addedPackages, requiresApproval: false, blocked: true, reason: "Project policy blocks new package installation.", auditCommand: null };
  }

  return { addedPackages, requiresApproval: true, blocked: false, reason: "Project policy requires approval before package installation.", auditCommand };
}

export function createDependencyApprovalRecord(projectId: string, decision: DependencyPolicyDecision, approvedAt = new Date()) {
  if (!decision.requiresApproval || decision.blocked || decision.addedPackages.length === 0) {
    return null;
  }

  return {
    projectId,
    packages: decision.addedPackages,
    approvedAt: approvedAt.toISOString(),
  } satisfies DependencyApprovalRecord;
}

function resolveProjectFilePath(workspacePath: string, relativePath: string) {
  if (path.isAbsolute(relativePath)) {
    throw new Error("Project file paths must be workspace-relative.");
  }

  const normalizedRelativePath = path.normalize(relativePath);
  const segments = normalizedRelativePath.split(path.sep);

  if (segments.some((segment) => segment === ".." || TRANSIENT_PATH_SEGMENTS.has(segment))) {
    throw new Error(`Unsafe generated project path: ${relativePath}`);
  }

  return assertInsideRoot(workspacePath, path.join(workspacePath, normalizedRelativePath));
}

async function listProjectSourceFiles(workspacePath: string, directory = workspacePath): Promise<string[]> {
  const entries = await fs.readdir(directory, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const entryPath = path.join(directory, entry.name);
      const relativePath = path.relative(workspacePath, entryPath);

      if (entry.isDirectory()) {
        if (TRANSIENT_PATH_SEGMENTS.has(entry.name)) {
          return [];
        }

        return listProjectSourceFiles(workspacePath, entryPath);
      }

      if (!SOURCE_EXTENSIONS.has(path.extname(entry.name))) {
        return [];
      }

      return [relativePath.split(path.sep).join(path.posix.sep)];
    }),
  );

  return files.flat();
}

function parsePackageDependencies(packageJson: string) {
  const parsed = JSON.parse(packageJson) as { dependencies?: Record<string, string>; devDependencies?: Record<string, string> };

  return new Set([...Object.keys(parsed.dependencies ?? {}), ...Object.keys(parsed.devDependencies ?? {})]);
}

function normalizeRoute(route: string) {
  const normalized = route.trim().startsWith("/") ? route.trim() : `/${route.trim()}`;

  return normalized.replace(/\/+$/, "") || "/";
}

function componentNameFromRoute(route: string) {
  if (route === "/") {
    return "HomePage";
  }

  return `${route
    .split("/")
    .filter(Boolean)
    .map((part) => part.split("-").map((word) => `${word.charAt(0).toUpperCase()}${word.slice(1)}`).join(""))
    .join("")}Page`;
}

function kebabCase(value: string) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .toLowerCase()
    .replace(/^-|-$/g, "");
}

function escapeSingleQuoted(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

function escapeJsxText(value: string) {
  return value.replace(/[{}<>]/g, "").replace(/\s+/g, " ").trim();
}

function isMissingPathError(error: unknown) {
  return typeof error === "object" && error !== null && "code" in error && error.code === "ENOENT";
}