import type { Metadata } from "next";
import { InspectorProvider } from "../components/inspector-provider";
import { ThemeProvider } from "../components/theme-provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "WebGL Particle Homepage",
  description: "A dark modern homepage with a native WebGL particle field generated by AppLoop.",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html className="dark" lang="en" suppressHydrationWarning>
      <body className="template-luminous-rings">
        <InspectorProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </InspectorProvider>
      </body>
    </html>
  );
}
