#!/usr/bin/env python3
"""Cat-ify the official algovivo quadruped mesh without breaking its trained policy.

The pretrained MLP walking policy expects the exact original topology: 62
vertices / 38 muscles. We append ear + tail geometry AFTER those indices, so
the policy keeps driving muscles [0..38) while scripted code sways only the
appended tail muscles. Physics simulates one soft body; the policy sees its
original sub-view (numVertices/numMuscles caps in the MLPPolicy constructor).

Appendage sizing was tuned headlessly against forward speed:
  base quadruped 1.71 u/s | tall raised tail 0.26 u/s | this layout 0.96 u/s
Keep appendages short + low: their inertia directly slows the trained walk.
"""
import json
import math

ROOT = "/Users/josoroma/projects/AppLoop/templates/algovivo-creature"

with open(f"{ROOT}/public/data/quadruped/mesh.json") as f:
    base = json.load(f)

V = [list(p) for p in base["pos"]]
TRIS = [list(t) for t in base["triangles"]]
MUSCLES = [list(m) for m in base["muscles"]]
L0 = list(base["l0"])
DEPTH = list(base["depth"])

POLICY_VERTEX_COUNT = len(V)
POLICY_MUSCLE_COUNT = len(MUSCLES)


def add(x, y, depth):
    V.append([round(x, 4), round(y, 4)])
    DEPTH.append(depth)
    return len(V) - 1


def tri(a, b, c):
    TRIS.append([a, b, c])


META_MUSCLES = []


def muscle(a, b, name, group):
    MUSCLES.append([a, b])
    META_MUSCLES.append({"name": name, "a": a, "b": b, "group": group, "index": len(MUSCLES) - 1})
    return len(MUSCLES) - 1


# ---------------------------------------------------------------- ears
# Perky triangles on the short head-top edges (28,23) and (27,8).
EAR_H = 0.26
p28, p23, p27, p8 = V[28], V[23], V[27], V[8]
ear_b_tip = add((p28[0] + p23[0]) / 2 - 0.02, max(p28[1], p23[1]) + EAR_H, 0.55)
ear_f_tip = add((p27[0] + p8[0]) / 2 + 0.10, max(p27[1], p8[1]) + EAR_H + 0.04, 0.55)
tri(28, 23, ear_b_tip)
tri(27, 8, ear_f_tip)

# ---------------------------------------------------------------- tail
# Short, gently raised tail off the rear-top edge (0,1). Longer/higher tails
# measurably slow the trained walk (inertia), so keep this compact.
t0 = add(-1.22, 1.62, -0.55)
t1 = add(-1.34, 1.76, -0.55)
t2 = add(-1.28, 1.92, -0.55)

tri(1, 0, t0)
tri(0, t0, t1)
tri(t0, t1, t2)

tail_muscles = [
    muscle(0, t0, "tail-anchor-a", "tail"),
    muscle(1, t0, "tail-anchor-b", "tail"),
    muscle(t0, t2, "tail-sway", "tail"),
]


# ---------------------------------------------------------------- derived
def dist(a, b):
    return math.hypot(V[a][0] - V[b][0], V[a][1] - V[b][1])


for a, b in MUSCLES[len(L0):]:
    L0.append(dist(a, b))

RSI = []
for a, b, c in TRIS:
    ax, ay = V[a]
    bx, by = V[b]
    cx, cy = V[c]
    m00, m10 = bx - ax, by - ay
    m01, m11 = cx - ax, cy - ay
    det = m00 * m11 - m01 * m10
    if abs(det) < 4e-3:
        raise SystemExit(f"near-degenerate triangle {[a, b, c]} det={det:.5f}")
    RSI.append([[m11 / det, -m01 / det], [-m10 / det, m00 / det]])

# sanity: original rsi preserved bit-for-bit intent (small float tolerance)
for i, cell in enumerate(base["rsi"]):
    for r in range(2):
        for c in range(2):
            if abs(cell[r][c] - RSI[i][r][c]) > 1e-3:
                raise SystemExit(f"rsi drift at triangle {i}")

mesh = {"pos": V, "triangles": TRIS, "muscles": MUSCLES, "l0": L0, "rsi": RSI, "depth": DEPTH}

meta = {
    "source": "cat-neural-walker-v4",
    "num_vertices": len(V),
    "num_triangles": len(TRIS),
    "num_muscles": len(MUSCLES),
    "policy_vertex_count": POLICY_VERTEX_COUNT,
    "policy_muscle_count": POLICY_MUSCLE_COUNT,
    "trunk_muscles": tail_muscles,
    "tail_anchor_count": 2,
    "ear_vertices": [ear_b_tip, ear_f_tip],
    "tail_vertices": [t0, t1, t2],
    "muscles": META_MUSCLES,
}

with open(f"{ROOT}/data/creature-mesh.json", "w") as f:
    json.dump(mesh, f)
with open(f"{ROOT}/data/creature-meta.json", "w") as f:
    json.dump(meta, f, indent=2)
with open(f"{ROOT}/public/data/cat/mesh.json", "w") as f:
    json.dump(mesh, f)

ts = f"""// Neural-walker cat: the official algovivo quadruped body (62 verts /
// 38 muscles, driven by the pretrained MLP walking policy) with cat ears and
// a raised tail appended AFTER the policy's index range. The policy keeps its
// exact original topology sub-view; scripted code sways only the tail.
// Generated by scripts/generate-cat-mesh.py — regenerate rather than hand-editing.

export type CreatureMesh = {{
  pos: number[][]
  triangles: number[][]
  muscles: number[][]
  l0: number[]
  rsi: number[][][]
  depth: number[]
}}

export const creatureMesh: CreatureMesh = {json.dumps(mesh)}

export const creatureMeta = {json.dumps(meta)}

export const MUSCLE_COUNT = {len(MUSCLES)}

// The pretrained policy only knows the original quadruped sub-system.
export const POLICY_VERTEX_COUNT = {POLICY_VERTEX_COUNT}
export const POLICY_MUSCLE_COUNT = {POLICY_MUSCLE_COUNT}
"""

with open(f"{ROOT}/lib/creature-mesh.ts", "w") as f:
    f.write(ts)

print(f"verts={len(V)} tris={len(TRIS)} muscles={len(MUSCLES)} (policy sub-view {POLICY_VERTEX_COUNT}v/{POLICY_MUSCLE_COUNT}m)")
