import type { Metadata } from "next";
import { InspectorProvider } from "../components/inspector-provider";
import { ThemeProvider } from "../components/theme-provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Deep Research Paper",
  description: "A rigorous deep research paper template generated by AppLoop.",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="template-deep-research-paper">
        <InspectorProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </InspectorProvider>
      </body>
    </html>
  );
}
